version: '3.7'

services:

  postgres:
    image: postgres:10.5
    restart: always
    container_name: DatenBank
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    ports:
      - '5433:5433'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U admin -d postgres'" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ../local-dev/migrations/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ../local-dev/migrations/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  backend:
    build:
      context: .
    ports:
      - 3000:3000
    healthcheck:
      test: "curl -k http://localhost:3000/customers/1"
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
  webportal:
    build:
      context: ./frontend/
    ports:
      - 4201:4200
    depends_on:
      backend:
        condition: service_healthy
